# Generated by Django 2.1.1 on 2018-10-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20181008_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookbookIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField(db_column='src', null=True)),
                ('title', models.CharField(db_column='title', max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, db_column='uploadtime', null=True)),
                ('pic', models.TextField(db_column='pic', null=True)),
                ('cookbookid', models.ForeignKey(db_column='cookbookid', null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.CookbookBasic')),
            ],
            options={
                'db_table': 'cookbook_index',
            },
        ),
    ]
