# Generated by Django 2.1.1 on 2018-10-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_cookbookindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbookfoodintro',
            name='foodsrc',
            field=models.TextField(db_column='foodsrc', null=True),
        ),
    ]
