# Generated by Django 2.1.1 on 2018-10-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_cookbookfoodintro_foodsrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbookstepupdate',
            name='stepid',
        ),
        migrations.RemoveField(
            model_name='cookbookstepupdate',
            name='userphone',
        ),
        migrations.DeleteModel(
            name='CookbookStepupdate',
        ),
    ]
