# Generated by Django 2.1.1 on 2018-10-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('cookbook', '0005_auto_20181009_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookbookStepupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('updatetime', models.DateField(auto_now_add=True, db_column='updateTime')),
                ('pic', models.TextField(db_column='pic')),
                ('isallow', models.IntegerField(blank=True, db_column='isAllow', null=True)),
                ('stepid', models.ForeignKey(db_column='stepId', on_delete=django.db.models.deletion.CASCADE, to='cookbook.CookbookMarche')),
                ('userphone', models.ForeignKey(db_column='userPhone', on_delete=django.db.models.deletion.CASCADE, to='user.UserLogin', to_field='userphone')),
            ],
            options={
                'db_table': 'cookbook_stepupdate',
            },
        ),
    ]
