# Generated by Django 2.1.1 on 2018-10-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_cookbookstepupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbookstepupdate',
            name='pic',
            field=models.TextField(db_column='pic', null=True),
        ),
    ]
