# Generated by Django 2.1.1 on 2018-10-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_auto_20181009_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbookfoodintro',
            name='gongxiao',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
