# Generated by Django 2.1.1 on 2018-10-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_cookbookcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbookcheck',
            name='cookbookid',
        ),
        migrations.RemoveField(
            model_name='cookbookcheck',
            name='userphone',
        ),
        migrations.DeleteModel(
            name='CookbookCheck',
        ),
    ]
