# Generated by Django 2.1.1 on 2018-10-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0010_auto_20181019_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbookstepupdate',
            name='stepid',
        ),
        migrations.RemoveField(
            model_name='cookbookstepupdate',
            name='userphone',
        ),
        migrations.DeleteModel(
            name='CookbookStepupdate',
        ),
    ]
