# Generated by Django 2.1.1 on 2018-10-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_userinform_usersign'),
        ('cookbook', '0012_cookbookstepupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookbookChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('updatetime', models.DateField(auto_now_add=True, db_column='updateTime')),
                ('pic', models.TextField(db_column='pic', null=True)),
                ('isread', models.IntegerField(blank=True, db_column='isRead', null=True)),
                ('phone', models.ForeignKey(db_column='phone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hephone', to='user.UserLogin', to_field='userphone')),
                ('stepid', models.ForeignKey(db_column='stepId', on_delete=django.db.models.deletion.CASCADE, to='cookbook.CookbookMarche')),
                ('userphone', models.ForeignKey(db_column='userPhone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myphone', to='user.UserLogin', to_field='userphone')),
            ],
            options={
                'db_table': 'cookbook_change',
            },
        ),
    ]
