# Generated by Django 2.1.1 on 2018-10-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'dynamic_comment',
            },
        ),
        migrations.CreateModel(
            name='DynamicLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dynamic_label',
            },
        ),
        migrations.CreateModel(
            name='DynamicPicuture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picturesrc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dynamic_picuture',
            },
        ),
        migrations.CreateModel(
            name='UserDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('time', models.DateField(auto_now_add=True, null=True)),
                ('picuture', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('userphone', models.ForeignKey(db_column='userPhone', on_delete=django.db.models.deletion.CASCADE, to='user.UserLogin', to_field='userphone')),
            ],
            options={
                'db_table': 'user_dynamic',
            },
        ),
        migrations.AddField(
            model_name='dynamicpicuture',
            name='dynamicid',
            field=models.ForeignKey(blank=True, db_column='dynamicId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.UserDynamic'),
        ),
        migrations.AddField(
            model_name='dynamiclabel',
            name='dynamicid',
            field=models.ForeignKey(blank=True, db_column='dynamicId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.UserDynamic'),
        ),
        migrations.AddField(
            model_name='dynamiccomment',
            name='dynamicid',
            field=models.ForeignKey(blank=True, db_column='dynamicId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.UserDynamic'),
        ),
        migrations.AddField(
            model_name='dynamiccomment',
            name='firstcomment',
            field=models.ForeignKey(blank=True, db_column='firstcomment', null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.DynamicComment'),
        ),
        migrations.AddField(
            model_name='dynamiccomment',
            name='userphone',
            field=models.ForeignKey(db_column='userPhone', on_delete=django.db.models.deletion.CASCADE, to='user.UserLogin', to_field='userphone'),
        ),
    ]
