# Generated by Django 2.1.1 on 2018-10-08 10:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_experience',
            },
        ),
        migrations.CreateModel(
            name='UserFans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanstime', models.DateField(auto_now_add=True, db_column='fansTime')),
            ],
            options={
                'db_table': 'user_fans',
            },
        ),
        migrations.CreateModel(
            name='UserHeadportrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_headportrait',
            },
        ),
        migrations.CreateModel(
            name='UserInform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernickname', models.CharField(blank=True, db_column='userNickname', max_length=18, null=True)),
                ('useremail', models.CharField(blank=True, db_column='userEmail', max_length=50, null=True)),
                ('userbriday', models.DateField(blank=True, db_column='userBriday', null=True)),
                ('userprovince', models.CharField(blank=True, db_column='userProvince', max_length=30, null=True)),
                ('usercity', models.CharField(blank=True, db_column='userCity', max_length=30, null=True)),
                ('usersex', models.IntegerField(blank=True, db_column='userSex', null=True)),
                ('headportraitid', models.ForeignKey(blank=True, db_column='headPortraitId', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserHeadportrait')),
            ],
            options={
                'db_table': 'user_inform',
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphone', models.CharField(db_column='userPhone', max_length=11, unique=True)),
                ('userpassword', models.CharField(db_column='userPassword', max_length=100)),
                ('isadmin', models.CharField(blank=True, max_length=20, null=True)),
                ('usernewlogintime', models.DateTimeField(auto_now=True, db_column='userNewLoginTime', null=True)),
                ('registtime', models.DateTimeField(auto_now_add=True, db_column='registTime')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
        migrations.CreateModel(
            name='UserOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user_occupation',
            },
        ),
        migrations.CreateModel(
            name='UserSignin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsigntime', models.DateField(auto_now=True, db_column='newSignTime', null=True)),
                ('lastsigntime', models.DateField(blank=True, db_column='lastSignTime', null=True)),
                ('userphone', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='user.UserLogin', to_field='userphone')),
            ],
            options={
                'db_table': 'user_signin',
            },
        ),
        migrations.AddField(
            model_name='userinform',
            name='professionid',
            field=models.ForeignKey(blank=True, db_column='professionId', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserOccupation'),
        ),
        migrations.AddField(
            model_name='userinform',
            name='userphone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserLogin', to_field='userphone'),
        ),
        migrations.AddField(
            model_name='userfans',
            name='beattephone',
            field=models.ForeignKey(db_column='beAtteUserPhone', on_delete=django.db.models.fields.related.ForeignKey, related_name='beatt', to='user.UserLogin', to_field='userphone'),
        ),
        migrations.AddField(
            model_name='userfans',
            name='phone',
            field=models.ForeignKey(db_column='userPhone', on_delete=django.db.models.fields.related.ForeignKey, related_name='att', to='user.UserLogin', to_field='userphone'),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='userphone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserLogin', to_field='userphone'),
        ),
        migrations.AlterUniqueTogether(
            name='userfans',
            unique_together={('phone', 'beattephone')},
        ),
    ]
