# Generated by Django 2.1.1 on 2018-10-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181013_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserYzm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphone', models.CharField(max_length=11)),
                ('dx', models.IntegerField(max_length=6)),
                ('dxtime', models.FloatField(max_length=255)),
            ],
            options={
                'db_table': 'user_yzm',
            },
        ),
    ]
