# Generated by Django 2.1.1 on 2018-10-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useryzm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useryzm',
            name='userphone',
        ),
        migrations.AddField(
            model_name='useryzm',
            name='telephone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='useryzm',
            name='dx',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='useryzm',
            name='dxtime',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
