# Generated by Django 2.1.1 on 2018-10-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181014_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserYzm',
        ),
    ]
