# Generated by Django 2.1.1 on 2018-10-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_useryzm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserYzm',
            fields=[
                ('telephone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('dx', models.CharField(max_length=6, null=True)),
                ('dxtime', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_yzm',
            },
        ),
    ]
