# Generated by Django 2.1.1 on 2018-10-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_useryzm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinform',
            name='usersign',
            field=models.CharField(blank=True, db_column='usersign', max_length=255, null=True),
        ),
    ]
